name: Bump version

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - main

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
