name: Vars

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - main

jobs:
  vars:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: view contexts
        run: echo $GITHUB_CONTEXT
